# Site settings
title: 
header-img: img/home-bg.png
email: tortillabar@me.com
copyright_name: zokratez
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  zokratez
learn_profile: zokratez
email_username: tortillabar@me.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
